import type { User, Chat, Property } from './types';
export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'MaxGoldHouse Admin' },
];
export const MOCK_CHATS: Chat[] = [
  { id: 'c1', title: 'MGH Support' },
];
export const MOCK_CHAT_MESSAGES: any[] = [];
const now = new Date().toISOString();
export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'p1',
    ref: 'MGH-001',
    kref: 'K-9901',
    title: 'Luxury Azure Villa',
    ptype: 'Villa',
    province: 'Alicante',
    town: 'Javea',
    location: 'Costa Blanca, Spain',
    area: 'Balcon al Mar',
    price: 1250000,
    originalprice: 1400000,
    frequency: 'Sale',
    beds: 4,
    baths: 3,
    living: 250,
    plot: 1000,
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'A stunning modern villa with panoramic sea views.',
    moredetails: 'Features high-end finishes throughout.',
    display: true,
    salestage: 0,
    rental: false,
    finca: false,
    penthouse: false,
    luxury: true,
    offplan: false,
    leasehold: false,
    golf: false,
    beach: true,
    aircon: true,
    pool: true,
    fireplace: true,
    heating: true,
    solarium: true,
    balconies: true,
    furnished: true,
    kitchen: true,
    utility: true,
    notrain: true,
    topsix: true,
    kyeroPrime: true,
    DE: 'Eine atemberaubende moderne Villa mit Panoramablick auf das Meer.',
    FR: 'Une superbe villa moderne avec vue panoramique sur la mer.',
    NL: 'Een prachtige moderne villa met panoramisch uitzicht op zee.',
    created: now,
    kdate: now,
    lastEdited: now
  },
  {
    id: 'p2',
    ref: 'MGH-002',
    kref: 'K-9902',
    title: 'Minimalist Beachfront Apartment',
    ptype: 'Apartment',
    province: 'Malaga',
    town: 'Marbella',
    location: 'Golden Mile',
    area: 'Puerto Banus',
    price: 850000,
    originalprice: 850000,
    frequency: 'Sale',
    beds: 2,
    baths: 2,
    living: 120,
    plot: 0,
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Elegant apartment steps from the beach.',
    moredetails: 'Recently renovated with luxury materials.',
    display: true,
    salestage: 1, // Reserved
    rental: false,
    finca: false,
    penthouse: false,
    luxury: false,
    offplan: false,
    leasehold: false,
    golf: false,
    beach: true,
    aircon: true,
    pool: true,
    fireplace: false,
    heating: true,
    solarium: false,
    balconies: true,
    furnished: true,
    kitchen: true,
    utility: false,
    notrain: true,
    topsix: false,
    kyeroPrime: false,
    DE: 'Elegante Wohnung nur wenige Schritte vom Strand entfernt.',
    FR: 'Appartement élégant à deux pas de la plage.',
    NL: 'Elegant appartement op een steenworp afstand van het strand.',
    created: now,
    kdate: now,
    lastEdited: now
  }
];